spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cg?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Wusd123..
  data:
    redis:
      host: localhost
      port: 6379            # Redis 端口
      password:             # 如果有密码可以在这里配置